// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ack

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Ack struct {
	_tab flatbuffers.Table
}

func GetRootAsAck(buf []byte, offset flatbuffers.UOffsetT) *Ack {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ack{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Ack) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ack) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Ack) Type() Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ack) MutateType(n Type) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func (rcv *Ack) SequenceNumber() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ack) MutateSequenceNumber(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func AckStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AckAddType(builder *flatbuffers.Builder, type_ int8) {
	builder.PrependInt8Slot(0, type_, 0)
}
func AckAddSequenceNumber(builder *flatbuffers.Builder, sequenceNumber uint32) {
	builder.PrependUint32Slot(1, sequenceNumber, 0)
}
func AckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
