// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ack

type Type = int8
const (
	TypeState Type = 0
	TypeConnection Type = 1
	TypeAck Type = 2
)

var EnumNamesType = map[Type]string{
	TypeState:"State",
	TypeConnection:"Connection",
	TypeAck:"Ack",
}

